name: 'Render Deploy action'
description: 'Instrument deploy to Render.com provider'
inputs:
  definition_file:
    description: 'Path to the render structured yaml definition file'
    required: true
  token:
    description: 'Render API token'
    required: true
  trigger_deploy:
    description: 'Should trigger the deploy to apply the changes after the definition file is processed - (true/false) default is true'
    required: false
  ignore_suspended:
    description: 'If a service is suspended, the action will ignore it and continue - (true/false) default is false'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'